name: Client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  code-quality:
    uses: ./.github/workflows/common-code-quality-checks.yml
    with:
      path: ./client
      # Skip type check for the client until we start implementing it
      skip-type-check: true
    secrets:
      API_SERVER_HOST: ${{ secrets.API_SERVER_HOST }}
      API_GRAPHQL_PATH: ${{ secrets.API_GRAPHQL_PATH }}
      API_GRAPHQL_SCHEMA_PATH: ${{ secrets.API_GRAPHQL_SCHEMA_PATH }}

  tests:
    uses: ./.github/workflows/common-tests.yml
    with:
      path: ./client
