name: Code Quality Checks

on:
  workflow_call:
    inputs:
      path:
        description: 'Working directory for the checks'
        required: true
        type: string

jobs:
  checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.path }}

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Setup Bun
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: bun install

      # Step 4: Type generation
      - name: Type Generation
        env:
          # Environment variables for the client
          VITE_API_SERVER_HOST: ${{ secrets.API_SERVER_HOST }}
          VITE_API_GRAPHQL_PATH: ${{ secrets.API_GRAPHQL_PATH }}
          VITE_API_GRAPHQL_SCHEMA_PATH: ${{ secrets.API_GRAPHQL_SCHEMA_PATH }}
        run: bun run type-generate

      # Step 4: Type-Check
      - name: Type-Check
        run: bun run type-check

      # Step 5: Lint Code
      - name: Lint Code
        run: bun run lint

      # Step 6: Check Formatting
      - name: Check Formatting
        run: bun run format:check
