name: Lint with Trunk

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint client folder with Trunk
        uses: trunk-io/trunk-action@v1
        with:
          working-directory: client

      - name: Lint server folder with Trunk
        uses: trunk-io/trunk-action@v1
        with:
          working-directory: server
